spring:
  # datasource 数据源配置内容
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
      

# mybatis 配置内容
mybatis:
  config-location: classpath:mybatis-config.xml # 配置 MyBatis 配置文件路径
  mapper-locations: classpath:mapper/*.xml # 配置 Mapper XML 地址
  type-aliases-package: com.example.demo.dataobject # 配置数据库实体包路径
